---
abstract: 'Time zone object base class and factory'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-TimeZone
requires:
  Class::Load: 0
  Class::Singleton: 1.03
  Cwd: 3
  Params::Validate: 0.72
  Pod::Man: 1.14
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DateTime-TimeZone
  repository: http://hg.urth.org/hg/DateTime-TimeZone
version: 1.27
