---
abstract: 'Time zone object base class and factory'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Copy: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  Storable: '0'
  Sys::Hostname: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  Test::Requires: '0'
  base: '0'
  lib: '0'
  overload: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime-TimeZone
provides:
  DateTime::TimeZone:
    file: lib/DateTime/TimeZone.pm
    version: '1.82'
  DateTime::TimeZone::Floating:
    file: lib/DateTime/TimeZone/Floating.pm
    version: '1.82'
  DateTime::TimeZone::Local:
    file: lib/DateTime/TimeZone/Local.pm
    version: '1.82'
  DateTime::TimeZone::Local::Android:
    file: lib/DateTime/TimeZone/Local/Android.pm
    version: '1.82'
  DateTime::TimeZone::Local::Unix:
    file: lib/DateTime/TimeZone/Local/Unix.pm
    version: '1.82'
  DateTime::TimeZone::Local::VMS:
    file: lib/DateTime/TimeZone/Local/VMS.pm
    version: '1.82'
  DateTime::TimeZone::OffsetOnly:
    file: lib/DateTime/TimeZone/OffsetOnly.pm
    version: '1.82'
  DateTime::TimeZone::OlsonDB:
    file: lib/DateTime/TimeZone/OlsonDB.pm
    version: '1.82'
  DateTime::TimeZone::OlsonDB::Change:
    file: lib/DateTime/TimeZone/OlsonDB/Change.pm
    version: '1.82'
  DateTime::TimeZone::OlsonDB::Observance:
    file: lib/DateTime/TimeZone/OlsonDB/Observance.pm
    version: '1.82'
  DateTime::TimeZone::OlsonDB::Rule:
    file: lib/DateTime/TimeZone/OlsonDB/Rule.pm
    version: '1.82'
  DateTime::TimeZone::OlsonDB::Zone:
    file: lib/DateTime/TimeZone/OlsonDB/Zone.pm
    version: '1.82'
  DateTime::TimeZone::UTC:
    file: lib/DateTime/TimeZone/UTC.pm
    version: '1.82'
requires:
  Class::Singleton: '0'
  Cwd: '3'
  File::Basename: '0'
  File::Compare: '0'
  File::Find: '0'
  File::Spec: '0'
  List::AllUtils: '0'
  List::Util: '0'
  Module::Runtime: '0'
  Params::Validate: '0.72'
  Try::Tiny: '0'
  constant: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DateTime-TimeZone
  homepage: http://metacpan.org/release/DateTime-TimeZone
  repository: git://github.com/autarch/DateTime-TimeZone.git
version: '1.82'
x_Dist_Zilla:
  perl:
    version: '5.016003'
  plugins:
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@DROLSKY/MakeMaker'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@DROLSKY/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@DROLSKY/AutoPrereqs'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@DROLSKY/CopyFilesFromBuild'
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - README.md
            - cpanfile
            - Makefile.PL
            - LICENSE
            - Build.PL
          exclude_match:
            - ^t/zd.*
          follow_symlinks: '0'
          include_dotfiles: '0'
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::GatherDir'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@DROLSKY/GitHub::Meta'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@DROLSKY/GitHub::Update'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@DROLSKY/MetaResources'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@DROLSKY/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.029'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@DROLSKY/MetaProvides::Package'
      version: '2.001002'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@DROLSKY/NextRelease'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@DROLSKY/PkgVersion'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@DROLSKY/TestMoreDoneTesting'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: '1'
          check_all_prereqs: '1'
          modules: []
          phase: release
          skip:
            - Dist::Zilla::Plugin::DROLSKY::Contributors
            - Dist::Zilla::Plugin::DROLSKY::License
      name: '@DROLSKY/stale modules, release'
      version: '0.032'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@DROLSKY/ReadmeMarkdownInBuild'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@DROLSKY/ReadmeMarkdownInRoot'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::Test::Pod::Coverage::Configurable
      name: '@DROLSKY/Test::Pod::Coverage::Configurable'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@DROLSKY/Test::PodSpelling'
      version: '2.006008'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@DROLSKY/Test::ReportPrereqs'
      version: '0.019'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@DROLSKY/ManifestSkip'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@DROLSKY/MetaYAML'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::License
      name: '@DROLSKY/License'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@DROLSKY/ExtraTests'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@DROLSKY/ExecDir'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@DROLSKY/ShareDir'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@DROLSKY/Manifest'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@DROLSKY/TestRelease'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@DROLSKY/ConfirmRelease'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@DROLSKY/UploadToCPAN'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@DROLSKY/CheckPrereqsIndexed'
      version: '0.013'
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@DROLSKY/CPANFile'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::DROLSKY::Contributors
      name: '@DROLSKY/DROLSKY::Contributors'
      version: '0.27'
    -
      class: Dist::Zilla::Plugin::DROLSKY::License
      name: '@DROLSKY/DROLSKY::License'
      version: '0.27'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::CheckFor::CorrectBranch'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::CheckFor::MergeConflicts'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          include_authors: '0'
          include_releaser: '1'
          order_by: name
          paths: []
      name: '@DROLSKY/Git::Contributors'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@DROLSKY/Git::Describe'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@DROLSKY/InstallGuide'
      version: '1.200005'
    -
      class: Dist::Zilla::Plugin::Meta::Contributors
      name: '@DROLSKY/Meta::Contributors'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@DROLSKY/MetaConfig'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@DROLSKY/MetaJSON'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::SurgicalPodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.008'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.008'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.008'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.008'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.008'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.008'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.008'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.008'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.008'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.008'
            -
              class: Pod::Weaver::Section::Contributors
              name: Contributors
              version: '0.008'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.008'
      name: '@DROLSKY/SurgicalPodWeaver'
      version: '0.0023'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@DROLSKY/PodSyntaxTests'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
      name: '@DROLSKY/Test::EOL'
      version: '0.16'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@DROLSKY/Test::NoTabs'
      version: '0.09'
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@DROLSKY/Test::Pod::LinkCheck'
      version: '1.001'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@DROLSKY/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - README.md
            - cpanfile
            - Makefile.PL
            - LICENSE
            - Build.PL
            - Changes
            - CONTRIBUTING.md
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::Check'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - README.md
            - cpanfile
            - Makefile.PL
            - LICENSE
            - Build.PL
            - Changes
            - CONTRIBUTING.md
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::Commit'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v1.82
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::Tag'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::Push'
      version: '2.029'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::OSPrereqs
      config:
        Dist::Zilla::Plugin::OSPrereqs:
          os: MSWin32
      name: MSWin32
      version: '0.005'
    -
      class: Dist::Zilla::Plugin::OSPrereqs
      config:
        Dist::Zilla::Plugin::OSPrereqs:
          os: hpux
      name: hpux
      version: '0.005'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@DROLSKY/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.029'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.029'
x_authority: cpan:DROLSKY
x_contributors:
  - 'Alexey Molchanov <alexey.molchanov@gmail.com>'
  - 'Alfie John <alfiej@fastmail.fm>'
  - 'Daisuke Maki <dmaki@cpan.org>'
  - 'David Pinkowitz <dave@pinkowitz.com>'
  - 'Iain Truskett <deceased>'
  - 'Joshua Hoblitt <jhoblitt@cpan.org>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Peter Rabbitson <ribasushi@cpan.org>'
